insert into public.exercises (name, slug, movement_pattern, primary_muscle, secondary_muscles, equipment, is_compound) values
('Barbell Back Squat', 'barbell_back_squat', 'squat', 'quads', '{glutes,hamstrings,core}', 'barbell', true),
('Barbell Front Squat', 'barbell_front_squat', 'squat', 'quads', '{glutes,core}', 'barbell', true),
('Barbell Deadlift', 'barbell_deadlift', 'hinge', 'hamstrings', '{glutes,back,core}', 'barbell', true),
('Romanian Deadlift', 'romanian_deadlift', 'hinge', 'hamstrings', '{glutes,back}', 'barbell', true),
('Sumo Deadlift', 'sumo_deadlift', 'hinge', 'hamstrings', '{glutes,quads,back}', 'barbell', true),
('Barbell Bench Press', 'barbell_bench_press', 'push', 'chest', '{shoulders,triceps}', 'barbell', true),
('Barbell Incline Bench Press', 'barbell_incline_bench_press', 'push', 'chest', '{shoulders,triceps}', 'barbell', true),
('Barbell Overhead Press', 'barbell_overhead_press', 'push', 'shoulders', '{triceps,core}', 'barbell', true),
('Barbell Bent Over Row', 'barbell_bent_over_row', 'pull', 'back', '{biceps,traps}', 'barbell', true),
('Barbell Pendlay Row', 'barbell_pendlay_row', 'pull', 'back', '{biceps,traps}', 'barbell', true),
('Barbell Hip Thrust', 'barbell_hip_thrust', 'hinge', 'glutes', '{hamstrings}', 'barbell', true),
('Dumbbell Bench Press', 'dumbbell_bench_press', 'push', 'chest', '{shoulders,triceps}', 'dumbbell', true),
('Dumbbell Incline Press', 'dumbbell_incline_press', 'push', 'chest', '{shoulders,triceps}', 'dumbbell', true),
('Dumbbell Shoulder Press', 'dumbbell_shoulder_press', 'push', 'shoulders', '{triceps}', 'dumbbell', true),
('Dumbbell Row', 'dumbbell_row', 'pull', 'back', '{biceps,traps}', 'dumbbell', true),
('Dumbbell Romanian Deadlift', 'dumbbell_romanian_deadlift', 'hinge', 'hamstrings', '{glutes}', 'dumbbell', true),
('Dumbbell Lunge', 'dumbbell_lunge', 'lunge', 'quads', '{glutes,hamstrings}', 'dumbbell', true),
('Dumbbell Bulgarian Split Squat', 'dumbbell_bulgarian_split_squat', 'lunge', 'quads', '{glutes}', 'dumbbell', true),
('Dumbbell Goblet Squat', 'dumbbell_goblet_squat', 'squat', 'quads', '{glutes,core}', 'dumbbell', true),
('Dumbbell Lateral Raise', 'dumbbell_lateral_raise', 'push', 'shoulders', '{}', 'dumbbell', false),
('Dumbbell Front Raise', 'dumbbell_front_raise', 'push', 'shoulders', '{}', 'dumbbell', false),
('Dumbbell Rear Delt Fly', 'dumbbell_rear_delt_fly', 'pull', 'shoulders', '{}', 'dumbbell', false),
('Dumbbell Bicep Curl', 'dumbbell_bicep_curl', 'pull', 'biceps', '{}', 'dumbbell', false),
('Dumbbell Hammer Curl', 'dumbbell_hammer_curl', 'pull', 'biceps', '{forearms}', 'dumbbell', false),
('Dumbbell Tricep Extension', 'dumbbell_tricep_extension', 'push', 'triceps', '{}', 'dumbbell', false),
('Dumbbell Skull Crusher', 'dumbbell_skull_crusher', 'push', 'triceps', '{}', 'dumbbell', false),
('Dumbbell Fly', 'dumbbell_fly', 'push', 'chest', '{}', 'dumbbell', false),
('Dumbbell Pullover', 'dumbbell_pullover', 'pull', 'back', '{chest}', 'dumbbell', false),
('Dumbbell Shrug', 'dumbbell_shrug', 'pull', 'traps', '{}', 'dumbbell', false),
('Machine Chest Press', 'machine_chest_press', 'push', 'chest', '{shoulders,triceps}', 'machine', true),
('Machine Incline Chest Press', 'machine_incline_chest_press', 'push', 'chest', '{shoulders,triceps}', 'machine', true),
('Machine Shoulder Press', 'machine_shoulder_press', 'push', 'shoulders', '{triceps}', 'machine', true),
('Machine Lat Pulldown', 'machine_lat_pulldown', 'pull', 'back', '{biceps}', 'machine', true),
('Machine Seated Row', 'machine_seated_row', 'pull', 'back', '{biceps,traps}', 'machine', true),
('Machine Chest Fly', 'machine_chest_fly', 'push', 'chest', '{}', 'machine', false),
('Machine Rear Delt Fly', 'machine_rear_delt_fly', 'pull', 'shoulders', '{}', 'machine', false),
('Leg Press', 'leg_press', 'squat', 'quads', '{glutes,hamstrings}', 'machine', true),
('Hack Squat', 'hack_squat', 'squat', 'quads', '{glutes}', 'machine', true),
('Leg Extension', 'leg_extension', 'squat', 'quads', '{}', 'machine', false),
('Leg Curl (Lying)', 'leg_curl_lying', 'hinge', 'hamstrings', '{}', 'machine', false),
('Leg Curl (Seated)', 'leg_curl_seated', 'hinge', 'hamstrings', '{}', 'machine', false),
('Calf Raise (Standing)', 'calf_raise_standing', 'core', 'calves', '{}', 'machine', false),
('Calf Raise (Seated)', 'calf_raise_seated', 'core', 'calves', '{}', 'machine', false),
('Smith Machine Bench Press', 'smith_machine_bench_press', 'push', 'chest', '{shoulders,triceps}', 'machine', true),
('Smith Machine Squat', 'smith_machine_squat', 'squat', 'quads', '{glutes}', 'machine', true),
('Hip Abductor Machine', 'hip_abductor_machine', 'core', 'glutes', '{}', 'machine', false),
('Hip Adductor Machine', 'hip_adductor_machine', 'core', 'glutes', '{}', 'machine', false),
('Glute Kickback Machine', 'glute_kickback_machine', 'hinge', 'glutes', '{hamstrings}', 'machine', false),
('Cable Lat Pulldown (Wide Grip)', 'cable_lat_pulldown_wide_grip', 'pull', 'back', '{biceps}', 'cable', true),
('Cable Lat Pulldown (Close Grip)', 'cable_lat_pulldown_close_grip', 'pull', 'back', '{biceps}', 'cable', true),
('Cable Row (Seated)', 'cable_row_seated', 'pull', 'back', '{biceps,traps}', 'cable', true),
('Cable Face Pull', 'cable_face_pull', 'pull', 'shoulders', '{traps}', 'cable', false),
('Cable Tricep Pushdown', 'cable_tricep_pushdown', 'push', 'triceps', '{}', 'cable', false),
('Cable Tricep Rope Extension', 'cable_tricep_rope_extension', 'push', 'triceps', '{}', 'cable', false),
('Cable Bicep Curl', 'cable_bicep_curl', 'pull', 'biceps', '{}', 'cable', false),
('Cable Lateral Raise', 'cable_lateral_raise', 'push', 'shoulders', '{}', 'cable', false),
('Cable Chest Fly', 'cable_chest_fly', 'push', 'chest', '{}', 'cable', false),
('Cable Crossover', 'cable_crossover', 'push', 'chest', '{}', 'cable', false),
('Cable Pull-Through', 'cable_pull_through', 'hinge', 'glutes', '{hamstrings}', 'cable', false),
('Cable Crunch', 'cable_crunch', 'core', 'core', '{}', 'cable', false),
('Pull-Up', 'pull_up', 'pull', 'back', '{biceps}', 'bodyweight', true),
('Chin-Up', 'chin_up', 'pull', 'back', '{biceps}', 'bodyweight', true),
('Push-Up', 'push_up', 'push', 'chest', '{shoulders,triceps,core}', 'bodyweight', true),
('Dip', 'dip', 'push', 'chest', '{triceps,shoulders}', 'bodyweight', true),
('Bodyweight Squat', 'bodyweight_squat', 'squat', 'quads', '{glutes}', 'bodyweight', false),
('Bodyweight Lunge', 'bodyweight_lunge', 'lunge', 'quads', '{glutes,hamstrings}', 'bodyweight', false),
('Plank', 'plank', 'core', 'core', '{}', 'bodyweight', false),
('Side Plank', 'side_plank', 'core', 'core', '{}', 'bodyweight', false),
('Glute Bridge', 'glute_bridge', 'hinge', 'glutes', '{hamstrings}', 'bodyweight', false),
('Hanging Leg Raise', 'hanging_leg_raise', 'core', 'core', '{}', 'bodyweight', false),
('Hanging Knee Raise', 'hanging_knee_raise', 'core', 'core', '{}', 'bodyweight', false),
('Mountain Climber', 'mountain_climber', 'core', 'core', '{}', 'bodyweight', false),
('Burpee', 'burpee', 'core', 'core', '{}', 'bodyweight', false),
('Kettlebell Swing', 'kettlebell_swing', 'hinge', 'glutes', '{hamstrings,back}', 'kettlebell', true),
('Kettlebell Goblet Squat', 'kettlebell_goblet_squat', 'squat', 'quads', '{glutes,core}', 'kettlebell', true),
('Kettlebell Clean', 'kettlebell_clean', 'pull', 'back', '{glutes,shoulders}', 'kettlebell', true),
('Kettlebell Press', 'kettlebell_press', 'push', 'shoulders', '{triceps}', 'kettlebell', true),
('Kettlebell Row', 'kettlebell_row', 'pull', 'back', '{biceps}', 'kettlebell', true),
('Turkish Get-Up', 'turkish_get_up', 'core', 'core', '{shoulders}', 'kettlebell', true),
('Barbell Curl', 'barbell_curl', 'pull', 'biceps', '{}', 'barbell', false),
('Barbell Skull Crusher', 'barbell_skull_crusher', 'push', 'triceps', '{}', 'barbell', false),
('Barbell Shrug', 'barbell_shrug', 'pull', 'traps', '{}', 'barbell', false),
('Barbell Calf Raise', 'barbell_calf_raise', 'core', 'calves', '{}', 'barbell', false),
('Barbell Good Morning', 'barbell_good_morning', 'hinge', 'hamstrings', '{back,glutes}', 'barbell', true),
('Barbell Reverse Lunge', 'barbell_reverse_lunge', 'lunge', 'quads', '{glutes,hamstrings}', 'barbell', true),
('Close Grip Bench Press', 'close_grip_bench_press', 'push', 'triceps', '{chest,shoulders}', 'barbell', true),
('Incline Bench Press', 'incline_bench_press', 'push', 'chest', '{shoulders,triceps}', 'barbell', true),
('Decline Bench Press', 'decline_bench_press', 'push', 'chest', '{triceps}', 'barbell', true),
('Dumbbell Step-Up', 'dumbbell_step_up', 'lunge', 'quads', '{glutes}', 'dumbbell', true),
('Dumbbell Reverse Lunge', 'dumbbell_reverse_lunge', 'lunge', 'quads', '{glutes,hamstrings}', 'dumbbell', true),
('Dumbbell Walking Lunge', 'dumbbell_walking_lunge', 'lunge', 'quads', '{glutes,hamstrings}', 'dumbbell', true),
('Dumbbell Side Lateral', 'dumbbell_side_lateral', 'push', 'shoulders', '{}', 'dumbbell', false),
('Dumbbell Concentration Curl', 'dumbbell_concentration_curl', 'pull', 'biceps', '{}', 'dumbbell', false),
('Dumbbell Reverse Fly', 'dumbbell_reverse_fly', 'pull', 'shoulders', '{traps}', 'dumbbell', false),
('Band Pull-Apart', 'band_pull_apart', 'pull', 'shoulders', '{traps}', 'band', false),
('Band Face Pull', 'band_face_pull', 'pull', 'shoulders', '{traps}', 'band', false),
('Band Tricep Pushdown', 'band_tricep_pushdown', 'push', 'triceps', '{}', 'band', false),
('Band Bicep Curl', 'band_bicep_curl', 'pull', 'biceps', '{}', 'band', false);

select count(*) as exercise_count from public.exercises;
-- Should be 98
