insert into public.exercises (name_en, name_th, movement_pattern, primary_muscle, secondary_muscles, equipment, is_compound) values
('Barbell Back Squat', 'สควอทบาร์เบล', 'squat', 'quads', '{glutes,hamstrings,core}', 'barbell', true),
('Barbell Front Squat', 'สควอทบาร์หน้า', 'squat', 'quads', '{glutes,core}', 'barbell', true),
('Barbell Deadlift', 'เดดลิฟท์บาร์เบล', 'hinge', 'hamstrings', '{glutes,back,core}', 'barbell', true),
('Romanian Deadlift', 'โรมาเนียนเดดลิฟท์', 'hinge', 'hamstrings', '{glutes,back}', 'barbell', true),
('Sumo Deadlift', 'ซูโม่เดดลิฟท์', 'hinge', 'hamstrings', '{glutes,quads,back}', 'barbell', true),
('Barbell Bench Press', 'เบนช์เพรสบาร์เบล', 'push', 'chest', '{shoulders,triceps}', 'barbell', true),
('Barbell Incline Bench Press', 'อินไคลน์เบนช์เพรส', 'push', 'chest', '{shoulders,triceps}', 'barbell', true),
('Barbell Overhead Press', 'โอเวอร์เฮดเพรสบาร์เบล', 'push', 'shoulders', '{triceps,core}', 'barbell', true),
('Barbell Bent Over Row', 'เบนท์โอเวอร์โรว์', 'pull', 'back', '{biceps,traps}', 'barbell', true),
('Barbell Pendlay Row', 'เพนเดลย์โรว์', 'pull', 'back', '{biceps,traps}', 'barbell', true),
('Barbell Hip Thrust', 'ฮิปทรัสต์บาร์เบล', 'hinge', 'glutes', '{hamstrings}', 'barbell', true),
('Dumbbell Bench Press', 'เบนช์เพรสดัมเบล', 'push', 'chest', '{shoulders,triceps}', 'dumbbell', true),
('Dumbbell Incline Press', 'อินไคลน์เพรสดัมเบล', 'push', 'chest', '{shoulders,triceps}', 'dumbbell', true),
('Dumbbell Shoulder Press', 'โชลเดอร์เพรสดัมเบล', 'push', 'shoulders', '{triceps}', 'dumbbell', true),
('Dumbbell Row', 'ดัมเบลโรว์', 'pull', 'back', '{biceps,traps}', 'dumbbell', true),
('Dumbbell Romanian Deadlift', 'โรมาเนียนเดดลิฟท์ดัมเบล', 'hinge', 'hamstrings', '{glutes}', 'dumbbell', true),
('Dumbbell Lunge', 'ลันจ์ดัมเบล', 'lunge', 'quads', '{glutes,hamstrings}', 'dumbbell', true),
('Dumbbell Bulgarian Split Squat', 'บัลแกเรียนสปลิทสควอท', 'lunge', 'quads', '{glutes}', 'dumbbell', true),
('Dumbbell Goblet Squat', 'กอบเล็ทสควอท', 'squat', 'quads', '{glutes,core}', 'dumbbell', true),
('Dumbbell Lateral Raise', 'ไซด์เลทเทอรัล', 'push', 'shoulders', '{}', 'dumbbell', false),
('Dumbbell Front Raise', 'ฟรอนเรซดัมเบล', 'push', 'shoulders', '{}', 'dumbbell', false),
('Dumbbell Rear Delt Fly', 'รีเดลฟลายดัมเบล', 'pull', 'shoulders', '{}', 'dumbbell', false),
('Dumbbell Bicep Curl', 'ไบเซ็พเคิลดัมเบล', 'pull', 'biceps', '{}', 'dumbbell', false),
('Dumbbell Hammer Curl', 'แฮมเมอร์เคิล', 'pull', 'biceps', '{forearms}', 'dumbbell', false),
('Dumbbell Tricep Extension', 'ไตรเซ็พเอ็กซ์เทนชัน', 'push', 'triceps', '{}', 'dumbbell', false),
('Dumbbell Skull Crusher', 'สกัลครัชเชอร์', 'push', 'triceps', '{}', 'dumbbell', false),
('Dumbbell Fly', 'ฟลายดัมเบล', 'push', 'chest', '{}', 'dumbbell', false),
('Dumbbell Pullover', 'พูลโอเวอร์ดัมเบล', 'pull', 'back', '{chest}', 'dumbbell', false),
('Dumbbell Shrug', 'ชรักดัมเบล', 'pull', 'traps', '{}', 'dumbbell', false),
('Machine Chest Press', 'เครื่องเพรสอก', 'push', 'chest', '{shoulders,triceps}', 'machine', true),
('Machine Incline Chest Press', 'เครื่องเพรสอกบน', 'push', 'chest', '{shoulders,triceps}', 'machine', true),
('Machine Shoulder Press', 'เครื่องเพรสไหล่', 'push', 'shoulders', '{triceps}', 'machine', true),
('Machine Lat Pulldown', 'แลทพูลดาวน์', 'pull', 'back', '{biceps}', 'machine', true),
('Machine Seated Row', 'ซีตโรว์', 'pull', 'back', '{biceps,traps}', 'machine', true),
('Machine Chest Fly', 'เพคเด็ค', 'push', 'chest', '{}', 'machine', false),
('Machine Rear Delt Fly', 'เครื่องรีเดลฟลาย', 'pull', 'shoulders', '{}', 'machine', false),
('Leg Press', 'เลกเพรส', 'squat', 'quads', '{glutes,hamstrings}', 'machine', true),
('Hack Squat', 'แฮคสควอท', 'squat', 'quads', '{glutes}', 'machine', true),
('Leg Extension', 'เลกเอ็กซ์เทนชัน', 'squat', 'quads', '{}', 'machine', false),
('Leg Curl (Lying)', 'เลกเคิลนอน', 'hinge', 'hamstrings', '{}', 'machine', false),
('Leg Curl (Seated)', 'เลกเคิลนั่ง', 'hinge', 'hamstrings', '{}', 'machine', false),
('Calf Raise (Standing)', 'แคล์ฟเรซยืน', 'core', 'calves', '{}', 'machine', false),
('Calf Raise (Seated)', 'แคล์ฟเรซนั่ง', 'core', 'calves', '{}', 'machine', false),
('Smith Machine Bench Press', 'สมิธมาชีนเบนช์', 'push', 'chest', '{shoulders,triceps}', 'machine', true),
('Smith Machine Squat', 'สมิธมาชีนสควอท', 'squat', 'quads', '{glutes}', 'machine', true),
('Hip Abductor Machine', 'เครื่องสะโพกออก', 'core', 'glutes', '{}', 'machine', false),
('Hip Adductor Machine', 'เครื่องสะโพกใน', 'core', 'glutes', '{}', 'machine', false),
('Glute Kickback Machine', 'เครื่องคิกแบ็คก้น', 'hinge', 'glutes', '{hamstrings}', 'machine', false),
('Cable Lat Pulldown (Wide Grip)', 'พูลดาวน์เคเบิลกว้าง', 'pull', 'back', '{biceps}', 'cable', true),
('Cable Lat Pulldown (Close Grip)', 'พูลดาวน์เคเบิลแคบ', 'pull', 'back', '{biceps}', 'cable', true),
('Cable Row (Seated)', 'เคเบิลโรว์', 'pull', 'back', '{biceps,traps}', 'cable', true),
('Cable Face Pull', 'เฟซพูล', 'pull', 'shoulders', '{traps}', 'cable', false),
('Cable Tricep Pushdown', 'ทรายเซ็พพุชดาวน์', 'push', 'triceps', '{}', 'cable', false),
('Cable Tricep Rope Extension', 'ทรายเซ็พโรปเอ็กซ์เทนชัน', 'push', 'triceps', '{}', 'cable', false),
('Cable Bicep Curl', 'เคเบิลไบเซ็พเคิล', 'pull', 'biceps', '{}', 'cable', false),
('Cable Lateral Raise', 'เคเบิลไซด์เรซ', 'push', 'shoulders', '{}', 'cable', false),
('Cable Chest Fly', 'เคเบิลเชสฟลาย', 'push', 'chest', '{}', 'cable', false),
('Cable Crossover', 'เคเบิลครอสโอเวอร์', 'push', 'chest', '{}', 'cable', false),
('Cable Pull-Through', 'เคเบิลพูลทรู', 'hinge', 'glutes', '{hamstrings}', 'cable', false),
('Cable Crunch', 'เคเบิลครันช์', 'core', 'core', '{}', 'cable', false),
('Pull-Up', 'พูลอัพ', 'pull', 'back', '{biceps}', 'bodyweight', true),
('Chin-Up', 'ชินอัพ', 'pull', 'back', '{biceps}', 'bodyweight', true),
('Push-Up', 'พุชอัพ', 'push', 'chest', '{shoulders,triceps,core}', 'bodyweight', true),
('Dip', 'ดิป', 'push', 'chest', '{triceps,shoulders}', 'bodyweight', true),
('Bodyweight Squat', 'สควอทตัวเปล่า', 'squat', 'quads', '{glutes}', 'bodyweight', false),
('Bodyweight Lunge', 'ลันจ์ตัวเปล่า', 'lunge', 'quads', '{glutes,hamstrings}', 'bodyweight', false),
('Plank', 'แพลงก์', 'core', 'core', '{}', 'bodyweight', false),
('Side Plank', 'ไซด์แพลงก์', 'core', 'core', '{}', 'bodyweight', false),
('Glute Bridge', 'กลูตบริดจ์', 'hinge', 'glutes', '{hamstrings}', 'bodyweight', false),
('Hanging Leg Raise', 'แฮงกิ้งเลกเรซ', 'core', 'core', '{}', 'bodyweight', false),
('Hanging Knee Raise', 'แฮงกิ้งนีเรซ', 'core', 'core', '{}', 'bodyweight', false),
('Mountain Climber', 'เมาน์เทนไคลม์เบอร์', 'core', 'core', '{}', 'bodyweight', false),
('Burpee', 'เบอร์ปี', 'core', 'core', '{}', 'bodyweight', false),
('Kettlebell Swing', 'เคทเทิลเบลสวิง', 'hinge', 'glutes', '{hamstrings,back}', 'kettlebell', true),
('Kettlebell Goblet Squat', 'เคทเทิลกอบเล็ทสควอท', 'squat', 'quads', '{glutes,core}', 'kettlebell', true),
('Kettlebell Clean', 'เคทเทิลคลีน', 'pull', 'back', '{glutes,shoulders}', 'kettlebell', true),
('Kettlebell Press', 'เคทเทิลเพรส', 'push', 'shoulders', '{triceps}', 'kettlebell', true),
('Kettlebell Row', 'เคทเทิลโรว์', 'pull', 'back', '{biceps}', 'kettlebell', true),
('Turkish Get-Up', 'เทอร์กิชเก็ทอัพ', 'core', 'core', '{shoulders}', 'kettlebell', true),
('Barbell Curl', 'เคิลบาร์เบล', 'pull', 'biceps', '{}', 'barbell', false),
('Barbell Skull Crusher', 'สกัลครัชเชอร์บาร์เบล', 'push', 'triceps', '{}', 'barbell', false),
('Barbell Shrug', 'ชรักบาร์เบล', 'pull', 'traps', '{}', 'barbell', false),
('Barbell Calf Raise', 'แคล์ฟเรซบาร์เบล', 'core', 'calves', '{}', 'barbell', false),
('Barbell Good Morning', 'กู๊ดมอร์นิ่ง', 'hinge', 'hamstrings', '{back,glutes}', 'barbell', true),
('Barbell Reverse Lunge', 'รีเวิร์สลันจ์', 'lunge', 'quads', '{glutes,hamstrings}', 'barbell', true),
('Close Grip Bench Press', 'โคลสกริปเบนช์', 'push', 'triceps', '{chest,shoulders}', 'barbell', true),
('Incline Bench Press', 'อินไคลน์เบนช์', 'push', 'chest', '{shoulders,triceps}', 'barbell', true),
('Decline Bench Press', 'ดีไคลน์เบนช์', 'push', 'chest', '{triceps}', 'barbell', true),
('Dumbbell Step-Up', 'สเต็พอัพดัมเบล', 'lunge', 'quads', '{glutes}', 'dumbbell', true),
('Dumbbell Reverse Lunge', 'รีเวิร์สลันจ์ดัมเบล', 'lunge', 'quads', '{glutes,hamstrings}', 'dumbbell', true),
('Dumbbell Walking Lunge', 'วอล์กกิ้งลันจ์', 'lunge', 'quads', '{glutes,hamstrings}', 'dumbbell', true),
('Dumbbell Side Lateral', 'ดัมเบลไซด์เลทเทอรัล', 'push', 'shoulders', '{}', 'dumbbell', false),
('Dumbbell Concentration Curl', 'คอนเซนเทรชันเคิล', 'pull', 'biceps', '{}', 'dumbbell', false),
('Dumbbell Reverse Fly', 'รีเวิร์สฟลาย', 'pull', 'shoulders', '{traps}', 'dumbbell', false),
('Band Pull-Apart', 'แบนด์พูลอะพาร์ท', 'pull', 'shoulders', '{traps}', 'band', false),
('Band Face Pull', 'แบนด์เฟซพูล', 'pull', 'shoulders', '{traps}', 'band', false),
('Band Tricep Pushdown', 'แบนด์ทรายเซ็พ', 'push', 'triceps', '{}', 'band', false),
('Band Bicep Curl', 'แบนด์ไบเซ็พ', 'pull', 'biceps', '{}', 'band', false);

select count(*) as exercise_count from public.exercises;
-- Should be 95
